name: revert-approve

on:
  pull_request:
    types:
      - opened

  workflow_dispatch:

jobs:
  approve:
    if:  startsWith(github.head_ref, 'revert-')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          gh pr review --approve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
